export const defaultTemplateStrings = [
	"appending *a thing* then *a list* gives *a list*",
	// "*an list* is the reverse of *a list*",
	// "*a date* is the same date as *a date*",
	// "*a number* is between *a number* & *a number*",
	// "*a date* is 1 day after *a date*",
	// "*a date* is *a number* days after *a date*",
	// "*a date* is immediately before *a date*",
	// "*a thing* is different from *a thing*",
	// "*a thing* is equivalent to *a thing*",
	// "*a thing* is of type *a type*",
	// "*a date* is not before *a date*",
	// "*a thing* is equal to *a thing*",
	// "*a date* is before *a date*",
	// "*a date* is after *a date*",
	// "*a thing* is in *a List*",
	// "*a thing* is *a thing*",
	// "*a thing* \\=@= *a thing*",
	// "*a thing* \\== *a thing*",
	// "*a thing* =\\= *a thing*",
	// "*a thing* =@= *a thing*",
	// "*a thing* == *a thing*",
	// "*a number* =< *a number*",
	// "*a number* >= *a number*",
	// "*a thing* = *a thing*",
];